(function(){
'use strict';
const phases=[
{id:0,title:'Orientation',track:'FOUNDATION',lessons:[['o1','Character model','Understand the contrast between public presentation and demonstrated capability.','CANON'],['o2','Evidence discipline','Separate anime evidence from reconstruction and fan interpretation.','CANON'],['o3','Operating vocabulary','Learn Observe, Control, Calculate, Execute and Adapt.','INFERRED']]},
{id:1,title:'Body Protocol',track:'PHYSICAL',lessons:[['b1','Posture','Relaxed upright alignment without theatrical stiffness.','INFERRED'],['b2','Movement economy','Reduce unnecessary fidgeting and gestures.','INFERRED'],['b3','Gaze','Use natural, attentive eye behavior.','INFERRED'],['b4','Basic maintenance','Protect sleep, food, hydration, hygiene and safe exercise.','SAFETY']]},
{id:2,title:'Voice Protocol',track:'COMMUNICATION',lessons:[['v1','Volume','Controlled, moderate vocal energy.','INFERRED'],['v2','Pace','Unhurried and clear without forcing a low pitch.','INFERRED'],['v3','Concise answers','Answer the actual question and remove filler.','INFERRED'],['v4','Silence','Allow useful silence without theatricality.','INFERRED']]},
{id:3,title:'Observation',track:'COGNITION',lessons:[['ob1','Facts vs assumptions','Separate what happened from what you think it means.','INFERRED'],['ob2','Relevant information','Focus attention on information that can change the outcome.','INFERRED'],['ob3','Unknowns','Keep uncertainty visible instead of filling gaps with guesses.','INFERRED'],['ob4','Evidence updates','Change the model when credible evidence changes.','INFERRED']]},
{id:4,title:'Reasoning Engine',track:'COGNITION',lessons:[['r1','Objective','Define the outcome before optimizing the route.','INFERRED'],['r2','Options','Generate realistic choices.','INFERRED'],['r3','Consequences','Compare likely outcomes and trade-offs.','INFERRED'],['r4','Decision threshold','Stop when additional analysis is no longer changing the choice.','INFERRED']]},
{id:5,title:'Emotion Control',track:'MENTAL',lessons:[['e1','Anger','Pause, identify the trigger and choose a proportionate response.','INFERRED'],['e2','Fear','Define the actual threat and separate possible from probable.','INFERRED'],['e3','Stress','Reduce load and perform the next concrete action.','INFERRED'],['e4','Failure','Analyze causes rather than turning results into identity judgments.','INFERRED']]},
{id:6,title:'Social Intelligence',track:'SOCIAL',lessons:[['s1','Listening','Understand before preparing a reply.','INFERRED'],['s2','Privacy','Share information intentionally and naturally.','INFERRED'],['s3','Trust','Update trust using evidence and experience.','INFERRED'],['s4','Conflict','Clarify, set a boundary, disengage or get appropriate help.','SAFETY']]},
{id:7,title:'Academic Academy',track:'SCHOOL',lessons:[['a1','Understand','Learn the mechanism before drilling it.','INFERRED'],['a2','Recall','Reproduce without looking at notes.','INFERRED'],['a3','Apply','Solve unfamiliar examples.','INFERRED'],['a4','Correct','Classify errors and repair the underlying weakness.','INFERRED']]},
{id:8,title:'Strategy Lab',track:'STRATEGY',lessons:[['st1','Scale to stakes','Match analysis depth to consequences.','INFERRED'],['st2','Reversible choices','Move faster when a choice is easy to undo.','INFERRED'],['st3','Information value','Gather information when it can improve a decision.','INFERRED'],['st4','Adaptation','Let reality update the plan.','INFERRED']]},
{id:9,title:'Pressure Room',track:'TRAINING',lessons:[['pr1','Time pressure','Prioritize instead of panic.','INFERRED'],['pr2','Unexpected questions','Pause, classify knowns and unknowns, then answer.','INFERRED'],['pr3','Social pressure','Do not let embarrassment choose your behavior.','INFERRED'],['pr4','Plan failure','Reset the strategy when it stops matching reality.','INFERRED']]},
{id:10,title:'Integration',track:'MASTERY',lessons:[['i1','Observe → Control','See clearly and regulate impulsive behavior.','INFERRED'],['i2','Calculate → Execute','Choose a reasonable action and do it.','INFERRED'],['i3','Adapt','Use results as feedback.','INFERRED'],['i4','Automaticity','Practice until the framework is easy to retrieve.','INFERRED']]}
];
const principles=['Observe before reacting.','Separate facts from assumptions.','Control behavior, not emotion.','Avoid unnecessary output.','Define the objective.','Protect useful information and privacy.','Let capability speak through results.','Update when evidence changes.','Scale thinking to the stakes.','Act once the decision is good enough.','Analyze causes, not identity.','Maintain sleep, food, hydration and recovery.','Do not invent hidden motives without evidence.','Keep relationships human.','Review and improve.'];
const kernel=[['OBSERVE','What actually happened?'],['CONTROL','What am I feeling, and what behavior can I choose?'],['CALCULATE','What is the objective, options and likely consequences?'],['EXECUTE','What is the next concrete action?'],['ADAPT','What did the result teach me?']];
const scenarios=[['Public insult','A classmate insults you in front of others and you feel a surge of anger.','Pause, separate facts from interpretation, then choose ignore/boundary/support based on the situation.'],['Someone keeps looking at you','You notice another student looking at you several times.','Keep the observation as a fact while leaving the reason uncertain without evidence.'],['Exam tomorrow','An exam is tomorrow and three topics are weak.','Prioritize weak/high-value topics, recall, solve representative questions, correct mistakes and sleep.'],['No obvious command','Your tasks are finished and you feel directionless.','Check safety and body needs and obligations, then choose the highest-value next action.']];
const lessons=phases.flatMap(p=>p.lessons.map(x=>({id:x[0],title:x[1],desc:x[2],tag:x[3],phase:p.title,track:p.track})));
const KEY='wr01-local-v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{section:'dashboard',completed:{},notes:{},profile:{name:'',studentId:'',className:'Grade 12',goal:'',bio:''},settings:{dailyGoal:30,showTags:true}};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const done=()=>Object.values(state.completed).filter(Boolean).length;
const pct=()=>Math.round(done()/lessons.length*100);
const badge=t=>`<span class="badge ${t==='CANON'?'canon':t==='INFERRED'?'infer':'safe'}">${t}</span>`;
function shell(body){const nav=[['dashboard','Command Center'],['curriculum','Curriculum'],['principles','Principles'],['training','Recall Lab'],['scenarios','Scenario Lab'],['school','Online School'],['chat','Chatroom'],['review','Daily Review'],['progress','Progress'],['instructor','Instructor Desk'],['settings','Settings'],['contact','Doubts / Contact']];return `<div class="app"><aside class="side"><div class="brand"><div class="micro">WR-01 / ACADEMY</div><h1>AYANOKOJI</h1><p>WHITE ROOM PROTOCOL</p></div><nav class="nav">${nav.map(x=>`<button class="${state.section===x[0]?'active':''}" data-nav="${x[0]}">${x[1]}</button>`).join('')}</nav><div class="sidefoot">Offline-first • No database • No API keys • No setup</div></aside><main class="main"><header class="top"><strong>${esc(nav.find(x=>x[0]===state.section)?.[1]||'Command Center')}</strong><span class="muted tiny">${esc(state.profile.name||'Student')} · ${pct()}%</span></header><section class="content">${body}<div class="footer">WR-01 • fictional character-study curriculum • local data</div></section></main></div>`}
function dashboard(){const n=lessons.find(x=>!state.completed[x.id])||lessons[0];return shell(`<div class="hero"><div class="micro">COMMAND CENTER</div><h2>Observe. Calculate. Execute. Adapt.</h2><p>A complete offline school-style curriculum with progress, recall, scenarios, profile, chat simulation and instructor desk.</p><div class="actions"><button class="btn primary" data-open="${n.id}">Continue ${esc(n.title)}</button><button class="btn" data-nav="progress">View progress</button></div></div><div class="grid"><div class="card"><div class="kpis"><div class="kpi"><div class="micro">Completion</div><strong>${pct()}%</strong></div><div class="kpi"><div class="micro">Completed</div><strong>${done()}</strong></div><div class="kpi"><div class="micro">Lessons</div><strong>${lessons.length}</strong></div><div class="kpi"><div class="micro">Mode</div><strong>LOCAL</strong></div></div></div><div class="card half"><div class="micro">MASTER KEY</div>${kernel.map((x,i)=>`<div class="step"><div class="num">${i+1}</div><div><strong>${x[0]}</strong><div class="tiny muted">${x[1]}</div></div></div>`).join('')}</div><div class="card half"><div class="micro">NEXT LESSON</div><h3>${esc(n.title)}</h3><p class="muted">${esc(n.desc)}</p>${badge(n.tag)}</div></div>`)}
function curriculum(){return shell(`<div class="hero"><div class="micro">CURRICULUM</div><h2>${phases.length} phases / ${lessons.length} lessons</h2><p>Complete lessons sequentially and track mastery.</p></div><div class="grid">${phases.map(p=>`<div class="card"><div class="micro">PHASE ${p.id} · ${p.track}</div><h3>${esc(p.title)}</h3><div class="list">${p.lessons.map(x=>`<div class="row"><div><strong>${state.completed[x[0]]?'✓ ':''}${esc(x[1])}</strong><div class="tiny muted">${esc(x[2])}</div></div><div class="actions">${state.settings.showTags?badge(x[3]):''}<button class="btn small" data-open="${x[0]}">${state.completed[x[0]]?'Review':'Learn'}</button></div></div>`).join('')}</div></div>`).join('')}</div>`)}
function principlesPage(){return shell(`<div class="hero"><div class="micro">PRINCIPLES</div><h2>15 core principles</h2><p>Use these as a framework, not as a replacement for your own identity.</p></div><div class="card"><ol>${principles.map(x=>`<li style="margin:10px 0">${esc(x)}</li>`).join('')}</ol></div>`)}
function progressPage(){return shell(`<div class="hero"><div class="micro">PROGRESS CENTER</div><h2>${pct()}% complete</h2><p>${done()} of ${lessons.length} lessons completed.</p></div><div class="card"><div class="progress"><span style="width:${pct()}%"></span></div><h3>Phase progress</h3>${phases.map(p=>{let d=p.lessons.filter(x=>state.completed[x[0]]).length;return `<div style="margin:14px 0"><div style="display:flex;justify-content:space-between"><strong>${esc(p.title)}</strong><span>${d}/${p.lessons.length}</span></div><div class="progress"><span style="width:${d/p.lessons.length*100}%"></span></div></div>`}).join('')}</div><div class="card"><div class="micro">STUDENT ID</div><h3>${esc(state.profile.studentId||'Not set')}</h3><p class="muted">${esc(state.profile.name||'Student')} · ${esc(state.profile.className)}</p></div>`)}
function lesson(id){let l=lessons.find(x=>x.id===id);state.section='curriculum';document.querySelector('#app').innerHTML=shell(`<div class="hero"><div class="micro">${esc(l.phase)} · ${esc(l.track)}</div><h2>${esc(l.title)}</h2><p>${esc(l.desc)}</p></div><div class="card"><div class="notice">Source: ${badge(l.tag)} This curriculum distinguishes documented character material from practical inference.</div><div class="actions" style="margin-top:18px"><button class="btn primary" data-complete="${id}">${state.completed[id]?'Mark incomplete':'Mark complete'}</button><button class="btn" data-nav="curriculum">Back</button></div></div>`)}
function training(){let q=lessons[(new Date().getDate()+new Date().getMonth())%lessons.length];return shell(`<div class="hero"><div class="micro">RECALL LAB</div><h2>Retrieve, don't reread.</h2><p>Explain the lesson from memory, then reveal the reference.</p></div><div class="card"><h3>${esc(q.title)}</h3><p class="muted">${esc(q.desc)}</p><button class="btn primary" data-reveal="${q.id}">Reveal reference</button><div id="reveal"></div></div>`)}
function scenariosPage(){return shell(`<div class="hero"><div class="micro">SCENARIO LAB</div><h2>Practice under uncertainty.</h2></div>${scenarios.map((s,i)=>`<div class="card" style="margin-bottom:16px"><h3>${esc(s[0])}</h3><p class="muted">${esc(s[1])}</p><div class="notice"><strong>Best response:</strong> ${esc(s[2])}</div></div>`).join('')}`)}
function school(){return shell(`<div class="hero"><div class="micro">ONLINE SCHOOL</div><h2>WR-01 Academy</h2><p>Everything runs directly in your browser. There is nothing to configure.</p></div><div class="grid"><div class="card half"><div class="micro">PROFILE</div><h3>${esc(state.profile.name||'Student')}</h3><p class="muted">${esc(state.profile.className)} · ${esc(state.profile.studentId||'No ID')}</p><button class="btn primary" data-nav="settings">Edit profile</button></div><div class="card half"><div class="micro">EXTERNAL STUDY</div><p><a class="btn" href="https://classroom.google.com/" target="_blank">Google Classroom</a></p><p><a class="btn" href="https://drive.google.com/" target="_blank">Google Drive</a></p><p><a class="btn" href="https://calendar.google.com/" target="_blank">Google Calendar</a></p></div></div>`)}
function chat(){let msgs=JSON.parse(localStorage.getItem('wr01-chat')||'[]');return shell(`<div class="hero"><div class="micro">CHATROOM</div><h2>Academy room</h2><p>Offline classroom simulation. Messages stay on this browser.</p></div><div class="card"><div id="msgs" style="max-height:420px;overflow:auto">${msgs.map(m=>`<div class="notice" style="margin:8px 0"><strong>${esc(m.name)}</strong> <span class="tiny muted">${esc(m.time)}</span><br>${esc(m.text)}</div>`).join('')||'<div class="empty">No messages yet.</div>'}</div><form id="chatForm" style="margin-top:15px"><input id="chatInput" maxlength="500" placeholder="Type a message…" required><button class="btn primary" type="submit">Send</button></form></div>`)}
function review(){let d=new Date().toISOString().slice(0,10);return shell(`<div class="hero"><div class="micro">DAILY REVIEW</div><h2>One useful review</h2><p>Write what worked, what failed and the next action.</p></div><div class="card"><textarea id="note" rows="8" placeholder="Today I observed…").replace?'' : ''></textarea><button class="btn primary" data-save-review>Save review</button><span id="saved" class="muted"></span></div>`)}
function settings(){return shell(`<div class="hero"><div class="micro">SETTINGS</div><h2>Student profile</h2></div><div class="card"><label>Name</label><input id="pname" value="${esc(state.profile.name)}"><label>Student ID</label><input id="pid" value="${esc(state.profile.studentId)}" placeholder="e.g. WR01-001"><label>Class</label><input id="pclass" value="${esc(state.profile.className)}"><label>Goal</label><input id="pgoal" value="${esc(state.profile.goal)}"><label>Bio</label><textarea id="pbio" rows="5">${esc(state.profile.bio)}</textarea><button class="btn primary" data-save-profile>Save profile</button><hr><button class="btn" data-export>Export backup</button> <label class="btn">Import backup<input id="import" type="file" accept="application/json" hidden></label> <button class="btn" data-reset>Reset local data</button></div>`)}
function instructor(){return shell(`<div class="hero"><div class="micro">INSTRUCTOR DESK</div><h2>Local classroom overview</h2><p>This setup-free version uses one browser profile. You can inspect your own stored student data and backup.</p></div><div class="grid"><div class="card"><div class="micro">STUDENT</div><h3>${esc(state.profile.name||'Unnamed')}</h3><p>ID: ${esc(state.profile.studentId||'Not set')}</p><p>Class: ${esc(state.profile.className)}</p></div><div class="card"><div class="micro">PERFORMANCE</div><h3>${pct()}%</h3><p>${done()} / ${lessons.length} lessons complete</p></div></div><div class="card"><div class="notice"><strong>Why no cloud?</strong> This version intentionally has no database, API key or server setup. A static GitHub Pages site cannot securely provide a shared multi-user instructor database by itself.</div></div>`)}
function contact(){return shell(`<div class="hero"><div class="micro">DOUBTS / CONTACT</div><h2>Ask for help</h2></div><div class="grid"><div class="card half"><h3>gauxarts@gmail.com</h3><a class="btn primary" href="mailto:gauxarts@gmail.com">Email</a></div><div class="card half"><h3>cyberjai2k25@gmail.com</h3><a class="btn primary" href="mailto:cyberjai2k25@gmail.com">Email</a></div></div>`)}
function render(){let b={dashboard,curriculum,principles:principlesPage,training,scenarios:scenariosPage,school,chat,review,progress:progressPage,instructor,settings,contact}[state.section]||dashboard;document.querySelector('#app').innerHTML=b()}
document.addEventListener('click',e=>{let n=e.target.closest('[data-nav]');if(n){state.section=n.dataset.nav;save();render();return}let o=e.target.closest('[data-open]');if(o){lesson(o.dataset.open);return}let c=e.target.closest('[data-complete]');if(c){state.completed[c.dataset.complete]=!state.completed[c.dataset.complete];save();lesson(c.dataset.complete);return}let r=e.target.closest('[data-reveal]');if(r){let q=lessons.find(x=>x.id===r.dataset.reveal);document.querySelector('#reveal').innerHTML=`<div class="notice" style="margin-top:15px">${esc(q.desc)}<br>${badge(q.tag)}</div>`;return}if(e.target.closest('[data-save-profile]')){state.profile.name=document.querySelector('#pname').value;state.profile.studentId=document.querySelector('#pid').value;state.profile.className=document.querySelector('#pclass').value;state.profile.goal=document.querySelector('#pgoal').value;state.profile.bio=document.querySelector('#pbio').value;save();render();return}if(e.target.closest('[data-save-review]')){let d=new Date().toISOString().slice(0,10);state.notes[d]=document.querySelector('#note').value;save();document.querySelector('#saved').textContent=' Saved locally.';return}if(e.target.closest('[data-export]')){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='wr01-backup.json';a.click();return}if(e.target.closest('[data-reset]')&&confirm('Reset all local WR-01 data?')){localStorage.removeItem(KEY);location.reload()}});
document.addEventListener('submit',e=>{if(e.target.id!=='chatForm')return;e.preventDefault();let i=document.querySelector('#chatInput'),t=i.value.trim();if(!t)return;let a=JSON.parse(localStorage.getItem('wr01-chat')||'[]');a.push({name:state.profile.name||'Student',text:t,time:new Date().toLocaleString()});localStorage.setItem('wr01-chat',JSON.stringify(a));render()});
document.addEventListener('change',async e=>{if(e.target.id==='import'&&e.target.files[0]){try{let x=JSON.parse(await e.target.files[0].text());if(!x.profile||!x.completed)throw Error('Invalid backup');state=x;save();render()}catch(err){alert(err.message)}}});
render();
})();
